--- 
title: "Super links"
author: "Lingyun Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
links-as-notes: true
colorlinks: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Preface {-}

This book collects super links.

# My books

1. https://zhanglynz.github.io/r_book_17_howtos/
1. https://zhanglynz.github.io/practicalR/
1. https://zhanglynz.github.io/sampling_b/
1. https://zhanglynz.github.io/understanding_sampling/
1. https://zhanglynz.github.io/tip_collection/
1. https://zhanglynz.github.io/my_lessons_in_using_R/
1. https://zhanglynz.github.io/elementary-maths/
1. https://zhanglynz.github.io/mathematical-experiments/
1. https://zhanglynz.github.io/algebra_notes/
1. https://zhanglynz.github.io/LearnGit/
1. https://zhanglynz.github.io/dealing_with_strings/
1. https://zhanglynz.github.io/dealing_with_big_data/
1. https://zhanglynz.github.io/rare_r_functions/
1. https://zhanglynz.github.io/python_notes/

# My homepage/blog

https://larryzhangnz.netlify.app/

# Videos

## Learn how to learn {-}

**URL**: https://www.youtube.com/watch?v=vd2dtkMINIw

Key ideas: focused mode vs. diffusion mode; sleep is important; chunks; recall; practice and repetition; brain muscles

Comments: It's great. Although, some parts may be kind of boring but I can and---I believe---you can as well get something very useful from watching the video. A tip: the QA part is wonderful.


# Books

## R related

1. Git doc, **URL:** https://docs.github.com/en/get-started/quickstart/github-flow

1. Git quick guide, **URL:** https://rogerdudler.github.io/git-guide/

1. Git hands-on session within RStudio, **URL:** https://inbo.github.io/git-course/course_rstudio.html

# Articles

## R related 

1. Top 7 Best R Shiny Books, **URL:** https://www.r-bloggers.com/2022/01/top-7-best-r-shiny-books-and-courses-that-are-completely-free/

    - Mastering Shiny by Hadley Wickham
    - Outstanding User Interfaces With Shiny by David Granjon
    - Engineering Production-Grade Shiny Apps by Colin Fay
    - The Shiny AWS Book by Matt Dancho
    - JavaScript 4 Shiny by Colin Fay
    - A gRadual intRoduction to Shiny by Ted Laderas
    - How to Start Shiny by RStudio
    
1. 

# Tools

1. https://quarto.org/
Quarto is an open-source scientific and technical publishing system built on Pandoc

1. https://www.rscreencasts.com/ 
Awesome data analysis screencasts from a top Data Scientist

1. https://www.r-bloggers.com/2022/05/software-development-resources-for-data-scientists/
Software Development Resources for Data Scientists